repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: spotless-check
        name: Spotless Check
        entry: ./gradlew spotlessCheck
        language: system
        pass_filenames: false
        stages: [commit]